"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""



def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    ### Please start your code here ###

    if s == "" or t == "":
        return ""

    lsS = list(s)
    lsT = list(t)

    for tval in lsT:
        if tval not in lsS:
            return tval

    ### End ###



"""

Below are the test cases I created for testing the correctness of your code.
Please don't modify them when you push the file back to GitHub
"""

if __name__ == '__main__':
        test0 = ("", "", "")
        test1 = ("abcd", "abcde", "e")
        test2 = ("asdfjkl","lkjaspdf","p")
        tests = [test0, test1, test2]
        for i, test in enumerate(tests):
                print "------------- Test " +str(i) + " -------------"
                print "-Test Input:"
                print test[0]
                print "-Expected Output:"
                print test[1]
                print "-Your Output:"
                your_ans = findTheDifference(test[0], test[1])
                print your_ans
                assert your_ans == test[2], "Wrong return. Please try again."
        print '\n**** Congratulations! You have passed all the tests! ****'


